language: java
jdk:
- oraclejdk8
- openjdk8
install: mvn install -U -DskipTests=true
script: mvn verify -U -Dmaven.javadoc.skip=true
after_success:
- util/update_snapshot_docs.sh
- util/deploy_snapshot.sh
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - secure: MJY016432HZC8lTgwtyWLzmjaKZNVxHWRZ1M3en4X4u0qsYd9mwpZKjbBry5M2GY1laeMwa2XX/hAicxaSqkijul6NGTkV1tSmAkRHccqyu80+5uQuK0SYRMzXPxZdHGwwYG1X9Myene7HDs2FyGg8UezQphfFQFk0y+0EFuFR4C2hrGUJl8OBjzx/sF9/MhyyUfdZPDHVxpZ/cmw+TspmBZ08IVjl5HJcYQGki/Y2VZ4d7rKfI24EeL5mjivFzWR3j6hWLKpRqbnCtMzcXDs/z8qBzWPIu8D+PZQpZwN6OQM/JDYpDD4Vn/9+FGStbjCGOtSTigvA7639NY7nKiGEWBJTEhREP+7YwovYcj9oPXodTYpNg/Ai1tgCHw2zGBiD2eandCCYhyN2gHcfdq2lJ1PA4nUPNdj1zsTW7IUNbAmJ+gVd4uDvgIML7NPqbgl9hUaEx/DPzVc272sOYJOdtRgcg5sOIA7Ehnky6CWnpKCggv2Lww3dO5bSeMccAoB96RQKNFqXTAynGoBaLZnVZzgCobZ66YAYWSosM0oBzWVwDEkw32MiRoizplF3NfnSARaGzENyCV4Gay611dbXYF9HVrxp3oYFnptEbvvOKmUGgp0HpQiBemzJ0tuabs4Zu47MkCnalrU9K8BkoreaVJk8WP0/KPj53t/fWVUT4=
  - secure: uLNJ12pDfeggkdcvV1G2KVgh04H7SkxRBPBsgmgMknu/6MnXZSlJS8uiT7bSId0E3F/ERXCjB/z00vI3+kYpvAYdvsNqGONx6rMJvFs+vn3BtG9q5VSyhULKrnZnkWthRYKQv5EZdQT8WqKVO77m266sX1eBGUtazazqwm8kEZ7yjagfiBNcfoUIdVEP1jCxd/0+Vdq/KRgtejunXmm6rcE9ppMh+j5KG6jy5FxwlfQzDXys+E+NvIsgFmMy7ZQKnivZuEhsQmng4nB8AaZpraOOrooNBJfVdn+VGiL8Pnw1INgOqv89LN5u6Hcc5ztL5Sf2rooSP21KQCLC1ZbtmqjXxng06AA4PIuTKdv75G/huK8M7q+TCWSpe/4aIjnRxOfqetQ3jntj6e1joolHVUWj/9cSOUwGIJg748SA6atN5iDi0GGfORutblD28/2BZzMOEMRKfszT0JGxQ5bsjbDzIbyvT+XrSpZ+exx/DAtMUzvn9OE+xDQW046pFy87UHPeW985vM9M1MVh1frT8RPq8pCIKVp+bLk8gJTvV+etfVkD6yT2YYwxtp/02s3G3IrQVF4WtuwXv0B0HUF94xwzVm+JtHEQ+v2Yq68z7IjApBlabocrUcWMNH1EiDgcscwQJ2xgdNEPyef3ruZYQ2TJaWeo/gyt0CmgfGyDAzc=
  - secure: Gi1cBOP9PiFiKDHHnId8hXGHjo4heNLN9XSsvKzSFG0fJzn889XWl3b6W4rGT4uqV3TvETe51rI/RdmD2Ru2W4oyoAk5ReE7rIyUFXmEHa1L/rfyNF8L0eAcKHS3ZpGIMk+k15kGJUxRKyloSTiqrXvIV96c7r9tfmZet5482uT+FiMNblrVwlWcguYzpUOpU2nHj57heueCIAWBVjS3/Fk1M8HwLFm07a7N8v9bvqN8Opc1a36FtIKxuHfCBWA0R+VwJLYEeW0RAUPnFQtVnq3ZKxOYqAiH+jdg4gDIX6i12/1VETQTjTkQt9uFVOtIooxWVMHt7Glho3/kBopUlnOOOsfmj40X/YP4u6tafcai0imXNtEVnjhUBX4f6+62QSl8GoJRvYwwKaJ1XL2Bz8W8kFvBj+rPRMF6495J4aAvn47ykxBM/gQvrMusjKyvku34jIpCeZ/XKUpUHQvErTQlp7dE1F94GaW4DDSBAFGBVrHPe0hGfRwRVglRZMmpDYj6yTl9xcsn+8iR2A8cN9JVumye10rKcAYIpy768uWarT4ZXv2eO1otxm2SUPlb6+ryxXKCyr0d6JfvG/o0Yq+Yg3mVBq4jgAvx4MzgP67tOKufBXcQP6+HKtNZrcHD0pWPassGb23io3/On68YObJpddgRBYes+lFLHOpzOmA=
branches:
  except:
  - gh-pages
